### PR TITLE
inlinedef fix trial

### PR DESCRIPTION
**Pull request by angerhang**
@dginev 
I am thinking about forcibly inserting `omdoc:CMP` if it is not found. Not quite sure if this will bring any harm.

### CODE REVIEW

**Comment by dginev** [comment]
It is important to understand why the CMP is missing, and under what circumstances. Patching without understanding the problem first may result in having 2 problems instead.

**Comment by angerhang** [comment]
Hmm....
I am being superficial again.
I originally thought `inlinedef` always needs to be wrapped inside `omdoc:CMP`, so it was nice to have the patch everywhere.

Your question is something I don't quite understand still.

For example if we have 
```latex
\begin{omtext}
 \inlinedef{\defii{machine}{state}, i.e. the values of variables}.
\end{omtext}
```
`omdoc:CMP` appears because of `omtext` for descriptive text.

but when we have 
```latex
\begin{itemize}
    \item \inlinedef{\defi{exceptions}: abort evaluation by signaling an exceptional}
\end{itemize}
```
we have no `omdoc:CMP`, so wouldn't it make sense to add one ourselves?

**Comment by dginev** [comment]
oh yes, we even used to have a special structure called CMP itemizations, just for these circumstances. It was a huge pain to maintain, I really hope we don't need to recreate it again.

But I don't remember any other details, you'd need to ask Michael. I think it was related to the fact that OMDoc could incorporate all of HTML natively, in which case the CMP wasn't always needed.

**Comment by kohlhase** [comment]
I have commented on #77 with a solution. We should (eventually) cancel this pull request and make an error message.

**Comment by angerhang** [comment]
I think the warning message has already been done from the last pull request.

https://github.com/KWARC/sTeX/blob/805a7220e1fd6494304c8cfa25101851a849a345/sty/statements/statements.dtx#L1374

**Comment by kohlhase** [comment]
I like my error message much better, could you update that?

**Comment by kohlhase** [comment]
and make a new pull request with the updated error message.

**Comment by angerhang** [comment]
You mean the original error message you had? 
```
 Can't call method "parentNode" on an undefined value at /path/to/localmh/ext/sTeX/sty/statements/statements.sty.ltxml line 285.
    In \inlinedef OptionalKeyVals:omtext{} from statements.sty.ltxml line 309
     <= \inlinedef{\defi{mutation}: allocatio... <= Core::Document[@0x65daf48] <= ␍\itemize@item\emph{input}/\emph{outp... <= ...
1 error; 1 fatal error at /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Common/Error.pm line 69.
```

**Comment by kohlhase** [comment]
no, the one at the end of #77

**Comment by angerhang** [comment]
That's odd. I don't see any. 


screen shot 2015-05-12 at 07 47 58

**Comment by kohlhase** [comment]
something went wrong,
The situation is the following (see the OMDoc schema at ```.../ext/sTeX/schema/rnc/omdoc*.rnc``` in particular the "Rich Text" module ```omdocrt.rnc```):
* the ```<o:omtext>```, ```<o:assertion>```, ...  elements (called "statements") have a ```<o:CMP>``` element that acts as a container for ```<h:p>```-like XHTML markup.  
* ```\inlinedef``` (and other inline statements like ```\inlineex```) goes to ```<ltx:text>``` and further to ```<h:span class='inlinedef'>``` in postprocessing. ```\inlinedef``` can occur anywhere inside a statement, i.e. inside its ```<o:CMP>```, in particular nested in a itemization,...  
* the problem with ```\inlinedef``` is that it may also contain ```\defi*```, which generate ```<o:symbol>``` elements which are not allowed in the XHTML rich text, but must be deposited ``outside`` the respective statement (and must be referenced in the ```<h:span>``` element). The ```<o:CMP>``` element is taken as the characteristic marker of the statement element.
For some reason this ```<o:CMP>``` is not found, but it should really really be there already, so we cannot (it would be illegal OMDoc) be just made. We have to find out the real reason why the ```<o:CMP>``` is not found and I just have. The ```\inlinedef``` is not inside a statement (Hang noticed that in #77; but I did not pay attention. 
What we really need is a good error message when we cannot find the ```<o:CMP>```: something like 
```
\inlinedef outside a statement! Try wrapping the paragraph in a 
\begin{omtext}, \begin{assertion}, \begin{axiom}, ... 
whatever is suitable semantically
```
I will make an error message in the LaTeX branch as well, so we should be able to route out these errors. We should close this

**Comment by kohlhase** [comment]
I already made an pushed the LaTeX error message

**Pull request closed without merging**
