### PR TITLE
Fix issue #45

### PR DESCRIPTION
**Pull request by La-Stravaganza**
I deleted ``\hbox`` and fixed the problem.

Test case:
```latex
\documentclass[notes]{mikoslides}
\newcommand{\sample}{Let life be beautiful like summer flowers And Death like autumn leaves.}
\newcommand{\comm}{Some comment words which will be reused again and again, and need to be long enough.}
\begin{document}
\begin{enumerate}
\item \sample \lec{\comm}
\item Different length test \lec{something}
\item \sample, by Rabindranath Tagore \lec{\comm} 
\end{enumerate}
\end{document}
```

Result:

selection_006

### CODE REVIEW

**Comment by kohlhase** [comment]
Great work. This is very helpful.

**Comment by kohlhase** [comment]
I have merged the pull request, but I am not quite sure that it went into the right direction. Could you make sure?

**Comment by La-Stravaganza** [comment]
I think it should be right. Since I first pulled from ``KWARC/sTeX``(which means my fork includes your recent changes), then I made the pull request.

For GenCS notes, I can't compile it. Many ``*.sms`` are not in repos, could you push them to the repos?
Mainly in:

https://gl.mathhub.info/MiKoMH/talks
https://gl.mathhub.info/MiKoMH/GenCS
https://gl.mathhub.info/MiKoMH/kwarc

I think these ``sms`` file should be in your computer and git ignored them.

For example,
``/root/localmh/MathHub/MiKoMH/kwarc/source/admin/en/academic-integrity.sms``

is needed, whereas it is missing.

**Comment by kohlhase** [comment]
Dear Jinbo,



On 03/04/15 17:48, Jinbo Zhang wrote:
>
> I think it should be right. Since I first pulled from
> |KWARC/sTeX|(which means my fork includes your recent changes), then I
> made the pull request.
>
OK, I will check.
>
> For GenCS notes, I can't compile it. Many |*.sms| are not in repos,
> could you push them to the repos?
> Mainly in:
>
> https://gl.mathhub.info/MiKoMH/talks
> https://gl.mathhub.info/MiKoMH/GenCS
> https://gl.mathhub.info/MiKoMH/kwarc
>
> I think these |sms| file should be in your computer and git ignored them.
>
Yes, I do not want to commit them. You have to make them yourself: go to
.../localmh/MathHub and invoke lmh gen --sms --localpaths

that takes a while but gives you all the sms (and localpaths) files.

Michael
>
> For example,
> |/root/localmh/MathHub/MiKoMH/kwarc/source/admin/en/academic-integrity.sms|
>
> is needed, whereas it is missing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/sTeX/pull/60#issuecomment-89334037>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by La-Stravaganza** [comment]
OK I get it. 
Still, ``/smglom/mv/source/fundefeq.tex`` is not in the repo.

**Comment by La-Stravaganza** [comment]
It seems that ``lmh`` using its own ``sTeX``, I think this is not so convinent for checking validlity of changes. Why not directly using the ``stex`` package inside ``texlive``, where I made the change?

**Comment by kohlhase** [comment]
the sTeX package in texlive is very old, when we have a more consistent state, I will make a new release. You have not made changes to texlive, but to the GIT repository, which is quite different. 
you can update the lmh sTeX with lmh selfupdate (I think, read the documentation).

**Comment by kohlhase** [comment]
```mv/fundefeq``` was an error in an importmodule, which I fixed a couple of days ago. Please pull.

**Comment by kohlhase** [comment]
I think this issue is solved.

**Comment by La-Stravaganza** [comment]
Yes, I know. When I was debugging, I substituted the old version in ``texlive`` with my newly testing one, and rebuilded ``ls-R``. This is the only way I can find to verify my changes. At least I think we should offer an option for using the ``sTeX`` package in ``texlive``.

And ``/localmh/MathHub/MiKoMH/GenCS/lib/lstmachines.tex`` is not found, after the pulling.

**Comment by kohlhase** [comment]
you should make issues to https://github.com/KWARC/localmh on this.

**Comment by kohlhase** [comment]
Oh, and you can (and should probably)  configure ```lmh``` to use your fork of sTeX. That will help you, you can do that with ```lmh config``` or just replace ```.../localmh/ext/sTeX``` by a clone of your fork.

**Pull request merged**
