### PR TITLE
Options handling...

### PR DESCRIPTION
**Pull request by angerhang**
Sync options handling with *.sty and *.cls with *.ltxml.

### CODE REVIEW

**Comment by kohlhase** [comment]
thanks for the pull request, but this is not what I want yet. You have only changed the  options in the ```*.sty.ltxml``` files. But remember that for most of the cases (except ```modules.sty.ltxml``` and a few others) the ```*.sty.ltxml``` files are generated from the corresponding ```*.dtx``` files. So your changes would be clobbered the next time I (or someone else generates them). So you have to actually do the changes in the ```*.dtx``` files and run ```make``` to get the changes you made direction. 
So please fix that first.

**Comment by angerhang** [comment]
I have just changed the *.dtx to cooperate our options handling, however, while I was running make.


Unfortunately, there are some other changes to various files at in various packages, which I didn't commit but need to be resolves. 

Specially these are differences between *.dtx, and *.cls, *cls.ltxml. Some of the changes I am not quite sure as I don't know which one to make, so I just discarded those changes, and am going to make an issue about that.

**Comment by angerhang** [comment]
Dear Michael,
     I think it will take me a while to digest to the discussion in our `LaTeXML` fork. So I thought it would be nice to make some progress in this repository too. All the options handlings should be good now and I will take a look at #67 and #61 today. 
     Do you think you can merge the pull request? : )

**Comment by angerhang** [comment]
I went through all the files again, and eliminates the differences between `*.dtx` and `*.cls`, `.sty`,`*.cls.ltxml` and `*.cls.ltxml`. Refer to #67 ,

Many files were changed, but I tried to double check all the changes that were made.

**Comment by angerhang** [comment]
It would better if we can merge this pull request before we make any more changes in #61.

**Comment by kohlhase** [comment]
Dear Hang,

I do not think that there is an open pull request. You have to make a
new one.


Michael

On 19/04/15 13:21, angerhang wrote:
>
> It would better if we can merge this pull request before we make any
> more changes in #61 <https://github.com/KWARC/sTeX/issues/61>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/sTeX/pull/66#issuecomment-94266885>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by kohlhase** [comment]
merged the pull request.

**Pull request merged**
