### PR TITLE
Fix document

### PR DESCRIPTION
**Pull request by angerhang**
I think a better flag for document id should be capitalized instead of using `document@id`, otherwise the double quotations marks in perl would try to interpolate `@id`.

With the new flag, when given:
```tex
\documentclass{omdoc}
\documentkeys{ID=foo}
\begin{document}
testing 

%\makeatletter keys: id = \document@id
\end{document}
```

sTeX produces 
```xml
<?xml version="1.0"?>
<!--This OMDoc document is generated from an sTeX-encoded one via LaTeXML, you
  may want to reconsider editing it.-->
<omdoc xmlns:omdoc="http://omdoc.org/ns" xmlns="http://omdoc.org/ns" xmlns:stex="http://kwarc.info/ns/sTeX"
 xml:id="foo" about="#foo" stex:srcref="/path/to/localmh/MathHub/smglom/mv/source/test.tex#textrange(from=3;0,to=0;0)">
<div xmlns="http://www.w3.org/1999/xhtml" id="p1" class="ltx_para">
<p id="p1.p1" class="ltx_p" about="#foo.p1.p1">testing</p>
</div></omdoc>
```

### CODE REVIEW

**Comment by angerhang** [comment]
This is for #178 and #177 .

**Comment by kohlhase** [comment]
> ```\documentkeys{ID=foo}```

this is not an option, the ```id``` key has to stay lowercase in the source. I do not really care what you do internally with it (you could still use ```DOCUMENTid``` (it seems that @dginev never had problems with ```@``` in internal macros though; ```@``` is the LaTeX (and LaTeXML) convention for "internal"/"not user-visible".), so please reconsider.

**Comment by angerhang** [comment]
Sure.

I changed it into `DOCUMENTid`, and now should be ready to merge.

Just a side note, `omdoc.dtx` doesn't seem to generate `omdoc.pdf` anymore, at least for my side after merging the master.

So we probably also want to look into that.

**Comment by kohlhase** [comment]
> Just a side note, omdoc.dtx doesn't seem to generate omdoc.pdf anymore, at least for my side after merging the master.
> 
> So we probably also want to look into that.

it does for me.

**Pull request merged**
