### PR TITLE
Path Canonicalization Finished

### PR DESCRIPTION
**Pull request by La-Stravaganza**
So this functionality is offered by package ``cpath``, with two main macros:

``\cpath{<some path>}`` will print the canonical path.
``\ComparePath{<path1>}{<path2>}`` will compare two paths, return true if their canonical paths are equal, else return false, and store this result in an if flag ``ifpath``.

Usage Example:

```latex
\documentclass{article}
\usepackage{cpath}

\def\result{%
\ifpath%
Equal.%
\else%
Not Equal.%
\fi%
}%

\begin{document}
\begin{enumerate}
	\item \ComparePath{/foo/bar/../baz}{/../../bar/../foo/baz}\result % both are /foo/baz
		\newline\cpath{/foo/bar/../baz}
		\newline\cpath{/../../bar/../foo/baz}
	\item \ComparePath{/test}{test/a}\result
	\item \ComparePath{/../foo/../..}{/}\result % two root dir
	\item \ComparePath{/a/b/../c}{/a/c/../b}\result
	\item \ComparePath{foo/bar/baz}{/foo/bar/baz}\result %treat equal
	\item \ComparePath{/foo///baz}{../foo/baz}\result % also support some non-standard way
\end{enumerate}
\end{document}
```

Results:

selection_023

Note:

I am not sure is this the best way to do the comparison. Originally I was planning something like ``\ifx{\cpath{<path 1>}}{\cpath{<path 2>}}``, but the result is not valid.

If you are happy about this way, I will document this package.

### CODE REVIEW

**Comment by La-Stravaganza** [comment]
@kohlhase any comment about this?

**Comment by kohlhase** [comment]
not yet. I will have time to see and comment soon.

**Comment by kohlhase** [comment]
I have looked at this, and I like it. However, I do not think that ```cpath.sty``` should have its own subdir, so I will move it into ```.../sty/modules/cpath.sty``` after merging.

**Comment by kohlhase** [comment]
Now, we must integrate this into modules.sty, I will make an issue out of this.

**Pull request merged**
