### PR TITLE
More argument type changes.

### PR DESCRIPTION
**Pull request by angerhang**
Should have included all needed changes for #202.

### CODE REVIEW

**Comment by kohlhase** [comment]
That looks much better (I had forgotten mhmodnl). But I am not sure that it works completely yet. I had been looking at 

```
\begin{module}[id=test_test]
\end{module}
```
and 
```
\begin{module}[id=test]
\gimport{test_test}
\end{module}
```
and this still gives me script warnings do you see these as well?

**Comment by kohlhase** [comment]
BTW, did you see 
https://github.com/KWARC/MMT/issues/95
this is probably quite useful for you.

**Comment by angerhang** [comment]
I have been waiting for this for a long time! Nice!

**Comment by dginev** [comment]
I am still unsure why no one likes ```killall -9 latexmls```, but if you have an alternative workflow you prefer, thumbs up :-)

**Comment by angerhang** [comment]
In fact I don't see the script warnings anymore using `module_fix` branch.

**Comment by angerhang** [comment]
Weirdly, `\gimpot` seems to have a strange path to look for the file to be imported, I have `test.tex` in 
```
/Users/yuancalvin/lmh/localmh/MathHub/MiKoMH/GenICT/source/python/en
``` 
but `gimport`is looking for the file in
```
/Users/yuancalvin/lmh/localmh/MiKoMH/GenICT/source/test_test.tex
```

If no path is specified, `\gimport` should assume the module to import is in the same directory isn't it?

**Comment by kohlhase** [comment]
> I am still unsure why no one likes killall -9 latexmls, but if you have an alternative workflow you prefer, thumbs up :-)

you can do that if you have access to the shell the server runs in. That is quite tedious in the docker-based workflow.

**Comment by kohlhase** [comment]
> f no path is specified, \gimport should assume the module to import is in the same directory isn't it?

I am not sure it does, but that would certatinly be a good default for the internal but I think that is what 
```
DefMacro('\mhcurrentrepos{}','\@mhcurrentrepos{#1}');
DefMacro('\@mhcurrentrepos{}','\def\mh@currentrepos{#1}\@@mhcurrentrepos{#1}');
DefConstructor('\@@mhcurrentrepos{}','',
  afterDigest => sub{ AssignValue('current_repos',ToString($_[1]->getArg(1)),'global'); } );
```
tries do do no?

**Pull request merged**
