### PR TITLE
CMML conversion in modules.sty.ltxml

### PR DESCRIPTION
**Pull request by angerhang**
See https://github.com/KWARC/sTeX/issues/41 for more info.

### CODE REVIEW

**Comment by angerhang** [comment]
I generated a few omdoc documents and they all complied with the schema.

@dginev should we merge this pull request?

**Comment by dginev** [comment]
I would like to hear that you manually inspected the generated math and saw with your own eyes that it looks good. Any Content Math will make valid omdoc, but the question is does it work as intended, at least on first sight.

I will give you a more detailed code review later.

If you're merging into a branch, go ahead, but we souldn't merge into master until we're sure this is done.

**Comment by angerhang** [comment]
Yeah I totally forgot that LaTeXML uses the schema to generate the eventual omdoc file. So it is true that just the schema validation is bootless.

**Comment by angerhang** [comment]
The changes entailed in modules.sty.ltxml seem to be fine, after several end-to-end comparisons. 

However the conversion to CMML is rather incomplete.

Merge the pull request into the new-content-mathml branch for now.

**Pull request merged**
