### PR TITLE
97 adjust dtx

### PR DESCRIPTION
**Pull request by cmaeder**
I called make in sty/statements. The .ltxml file did not change. However make failed with

```
maeder@lati:~/sTeX/sty/statements$ make
pdflatex -interaction batchmode -file-line-error statements.ins
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
pdflatex -interaction batchmode -file-line-error statements.dtx
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
../make/Makefile.in:27: recipe for target 'statements.pdf' failed
make: *** [statements.pdf] Error 1
```

Merging should be uncritical. @dginev do so.

### CODE REVIEW

**Comment by dginev** [comment]
I think if make fails no file would change. But this is the right fix (and really, the executable bit was on? Oh my.) Thanks, merging!

**Comment by kohlhase** [comment]
can you tell me a bit more what the error is, for me ```make -B``` runs through. 
But I fear that the problem may be that you do not have access to the bib files.

**Comment by cmaeder** [comment]
```
maeder@lati:~/sTeX/sty/statements$ make -B
pdflatex -interaction batchmode -file-line-error statements.ins
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
pdflatex -interaction batchmode -file-line-error statements.ins
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
pdflatex -interaction batchmode -file-line-error statements.dtx
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
../make/Makefile.in:27: recipe for target 'statements.pdf' failed
make: *** [statements.pdf] Error 1
```

**Comment by kohlhase** [comment]
hmmm, that does not help. But I have fixed the bib handling. Can you please try again>?

**Comment by cmaeder** [comment]
I got `! LaTeX Error: File `biblatex.sty' not found.` by just pdflatex on statements.dtx.

After your fix it works now!

**Comment by kohlhase** [comment]
wonderfull, then we can close right?

**Pull request merged**
