### PR TITLE
New content mathml

### PR DESCRIPTION
**Pull request by angerhang**

### CODE REVIEW

**Comment by kohlhase** [comment]
Hang, you should just merge this yourself. I think you should be able to (otherwise we need to fix that).

**Comment by angerhang** [comment]
Move over to the KWARC/sTeX/new-content-mathml branch

**Comment by angerhang** [comment]
Yeah I was in the process of moving : )

**Comment by kohlhase** [comment]
hmmm, I cannot see the generate file test.omdoc did you push that?

**Comment by angerhang** [comment]
Sorry I thought it would be nice to not include that in the repository. The makefile should let you generate omdoc, but either way the output is the following. 

```xml
<?xml version="1.0"?>
<!--This OMDoc document is generated from an sTeX-encoded one via LaTeXML, you
  may want to reconsider editing it.-->

<omdoc xmlns:omdoc="http://omdoc.org/ns" xmlns="http://omdoc.org/ns" xmlns:stex="http://kwarc.info/ns/sTeX" xmlns:om="http://www.openmath.org/OpenMath" xmlns:m="http://www.w3.org/1998/Math/MathML" xml:id="omdoc1" about="#omdoc1" stex:srcref="/path/to/localmh/ext/sTeX/cmmltest/test.tex#textrange(from=3;1,to=0;0)">

<div xmlns="http://www.w3.org/1999/xhtml" id="p1" class="ltx_para">
<p id="p1.p1" class="ltx_p" about="#omdoc1.p1.p1">[creators=miko]relationen</p>
</div>
<omdoc:omtext type="definition" xml:id="relation.def" about="#relation.def" stex:srcref="/path/to/localmh/ext/sTeX/cmmltest/test.tex#textrange(from=6;0,to=9;16)">

<omdoc:CMP xml:id="relation.def.CMP1" about="#relation.def.CMP1" stex:srcref="/path/to/localmh/ext/sTeX/cmmltest/test.tex#textrange(from=6;0,to=9;16)">

    <p xmlns="http://www.w3.org/1999/xhtml" id="relation.def.CMP1.p1" class="ltx_p" about="#relation.def.CMP1.p1" stex:srcref="/path/to/localmh/ext/sTeX/cmmltest/test.tex#textrange(from=6;67,to=7;26)">
       <m:math xmlns="http://dlmf.nist.gov/LaTeXML" about="#relation.def.CMP1.p1.m1" alttext="\sseteq{R}{\pairs{A}B}" display="inline" stex:srcref="/path/to/localmh/ext/sTeX/cmmltest/test.tex#textrange(from=6;67,to=7;26)">
         <m:mrow>
          <m:merror class="ltx_ERROR undefined undefined">
          <m:mtext>\sseteq</m:mtext>
          </m:merror>
         <m:mo>&#x2062;</m:mo>
         <m:mi>R</m:mi>
         <m:mo>&#x2062;</m:mo>
        <m:merror class="ltx_ERROR undefined undefined">
         <m:mtext>\pairs</m:mtext>
        </m:merror>
        <m:mo>&#x2062;</m:mo>
        <m:mi>A</m:mi>
        <m:mo>&#x2062;</m:mo>
        <m:mi>B</m:mi> 
      </m:mrow>
     </m:math> 
is a (binary) 
    <omdoc:term name="relation" role="definiendum" xml:id="relation.def.CMP1.p1.term2" about="#relation.def.CMP1.p1.term2" stex:srcref="/path/to/localmh/ext/sTeX/cmmltest/test.tex#textrange(from=6;20,to=7;57)">relation</omdoc:term> between 
    <m:math xmlns="http://dlmf.nist.gov/LaTeXML" about="#relation.def.CMP1.p1.m2" alttext="A" display="inline" stex:srcref="/path/to/localmh/ext/sTeX/cmmltest/test.tex#textrange(from=6;10,to=7;68)">
       <m:mi >A</m:mi>
   </m:math> and
   <m:math xmlns="http://dlmf.nist.gov/LaTeXML" about="#relation.def.CMP1.p1.m3" alttext="B" display="inline" stex:srcref="/path/to/localmh/ext/sTeX/cmmltest/test.tex#textrange(from=6;2,to=7;76)">  
    <m:mi>B</m:mi>
   </m:math>.
If 
  <m:math xmlns="http://dlmf.nist.gov/LaTeXML" about="#relation.def.CMP1.p1.m4" alttext="A=B" display="inline" stex:srcref="/path/to/localmh/ext/sTeX/cmmltest/test.tex#textrange(from=7;50,to=8;10)">
    <m:mrow>
    <m:mi>A</m:mi>
    <m:mo>=</m:mo>
    <m:mi>B</m:mi>
   </m:mrow>
  </m:math> then 
  <m:math xmlns="http://dlmf.nist.gov/LaTeXML" about="#relation.def.CMP1.p1.m5" alttext="R" display="inline" stex:srcref="/path/to/localmh/ext/sTeX/cmmltest/test.tex#textrange(from=7;39,to=8;19)">
   <m:mi>R</m:mi>
   </m:math> is called a 
   <omdoc:term name="relation-on" role="definiendum" xml:id="relation.def.CMP1.p1.term7" about="#relation.def.CMP1.p1.term7" stex:srcref="/path/to/localmh/ext/sTeX/cmmltest/test.tex#textrange(from=7;4,to=8;53)">relation on</omdoc:term>
    <m:math xmlns="http://dlmf.nist.gov/LaTeXML" about="#relation.def.CMP1.p1.m6" alttext="A" display="inline" stex:srcref="/path/to/localmh/ext/sTeX/cmmltest/test.tex#textrange(from=7;2,to=8;56)">  
      <m:mi>A</m:mi>
   </m:math>.</p>
</omdoc:CMP>
</omdoc:omtext>
</omdoc>

```

**Comment by kohlhase** [comment]
I think it would be good to have the generated files in the repos, so that we can communicate more easily.

**Comment by angerhang** [comment]
Sure, why not. 

Just one remark about if there is any thing maybe an emacs script to better the omdoc indentation? 
I know omdoc is not designed for human readability. 

However sometimes it gets quite grueling when one needs to compare two omdoc files, the format of which is not human friendly.

**Comment by angerhang** [comment]
Or we will have to indent the omdoc files line by line ourselves : o

**Comment by kohlhase** [comment]
I use nxml-mode, which is quite good at navigating XML. 
Also, you can indent ```foo.xml``` with ```xmllint --format foo.xml```.

**Comment by angerhang** [comment]
Ok thanks!

**Pull request merged**
