### PR TITLE
Change parameter type for \importmodule and \usemodule.

### PR DESCRIPTION
**Pull request by angerhang**
Patch for #202 .

### CODE REVIEW

**Comment by dginev** [comment]
Btw, I think you should also consider changing the Parameter types for ```\importmoduleI``` and ```\importmodulevia``` to Semiverbatim, since the underscore name could end up in either of those. And you can check for other macros that seem to be likely victims of the behaviour.

**Comment by angerhang** [comment]
Yes your are right. I just added other ones that might also be influenced by argument type.

**Comment by dginev** [comment]
Looks good.

**Comment by kohlhase** [comment]
Ah good catch. But I think there are still ```\importmhmodule``` and ```\usemhmodule``` from ```module-mh.sty.ltxml``` (```mathhub.dtx```) and ```\gimport``` and ```\guse``` from ```smglom.dtx```.

**Comment by angerhang** [comment]
Totally forget about the module stuff in mathhub.

**Pull request merged**
