### PR TITLE
script for font installation under debian/ubuntu

### PR DESCRIPTION
**Pull request by cmaeder**
maybe this script can be added. I'm not sure if its purpose should be documented elsewhere.

### CODE REVIEW

**Comment by La-Stravaganza** [comment]
I think the installation of these two fonts has already been integrated inside dockerfile. But it will still be beneficial for someone who wants to install them manually.

**Comment by cmaeder** [comment]
Where do the fonts files originally come from? (This should be documented.) It may make more sense to get the fonts from an official source rather than keeping copies here.

**Comment by La-Stravaganza** [comment]
Fandol Fonts: https://www.ctan.org/tex-archive/fonts/fandol?lang=en
cwTeX Fonts: https://github.com/l10n-tw/cwtex-q-fonts-TTFs/releases

**Comment by kohlhase** [comment]
thanks, merged

**Pull request merged**
