### PR TITLE
first tests

### PR DESCRIPTION
**Pull request by cmaeder**
I've activated travis tests for this repository to (hopefully) earlier detect stupid commits to the master branch.

The build history is here: https://travis-ci.org/KWARC/sTeX/builds
If you click on "branches" https://github.com/KWARC/sTeX/branches you should see failed or successful tests. (The current failure for master is due to a missing `.travis.yml` file that will be added by this pull request.)

For the tests (parts of) texlive_2012, biber and latexml are installed. And then `make` is called in `STEXDIR`. 

There are still some pdf errors that I could not sort out, but these errors do not cause `make` (and thus `travis`) to fail.

I made some changes in `dcm`, namely omitting `dcmi`, deleting `creator` and adding `\omdoc` in order to avoid pdf errors. Please review this!

The other (non-failing) errors are probably caused by the old `biblatex` version, but I did not know how to install a newer `texlive` version.

I've also added a `.sms` file that seemed to be missing and could not be generated (due to a missing program for it).

### CODE REVIEW

**Comment by cmaeder** [comment]
The failure in omdoc is

```
./omdoc.bbl:21: Undefined control sequence.
l.21   \sortlist
                {entry}{anyt}
...
./omdoc.bbl:175: Undefined control sequence.
l.175   \endsortlist
```

**Comment by kohlhase** [comment]
this sounds like a biblatex problem, maybe the version you installed is too old?

**Comment by cmaeder** [comment]
Installing texlive-2015 via http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz failed with

```
Your test run exceeded 50 minutes. 
```

**Comment by cmaeder** [comment]
@kohlhase Are you sure that my changes to the other files are sane? (And are not just made by me to get it through with an old texlive installation?)

Let me know when I should make a pull-request to revert changes

**Comment by kohlhase** [comment]
no, that is OK.

**Pull request merged**
